### ISSUE TITLE
Setup Camel based routing and queues for provenance services

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/provenance-service#1]
#### Description
Provenance service should intercept every message that goes through the activeMQ. This can be implemented using Camel routes and provenance specific queues that are consumed by the ProvenanceService. 

This implementation should allows us to get the communication related provenance data. 

#### DoD

Working queues and routing. 

#### Testing

Skip it  for now.

**Comment by blankdots** [comment]
References:
* http://camel.apache.org/activemq.html
* http://camel.apache.org/routes.html
* Camel includes the following Component implementations via URIs. http://camel.apache.org/components.html
* Camel can interact with Etcd (kontena.io ? ) http://camel.apache.org/etcd.html as well as with Consul http://camel.apache.org/consul-component.html

Examples:
* https://github.com/kkvinodkumaran/camel (tutorial here: http://www.pretechsol.com/2013/08/apache-camel-activemq-example_26.html)
* http://blog.kopis.de/2015/06/14/microservices-with-apache-camel/
* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_A-MQ/6.2/html/Security_Guide/CamelComps-ActiveMQConfig.html
