### ISSUE TITLE
Handling/logging message related errors with messagebroker

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/provenance-service#21]
#### Description
Current implementation leaves the invalid messages to the queue by not acknowledging them and that causes weird errors and would require manual purging of the messages. 

Possible solutions:
* Error queues
* acknowledge and raise error
* can validation be implemented in the broker?
* how are the messages in the error queue processed?
* routing based implementation (Camel?)

#### DoD
Better error handling for services 

#### Testing
Integration testing

**Comment by blankdots** [comment]
https://stackoverflow.com/questions/28604332/rabbitmq-ack-or-nack-leaving-messages-on-the-queue
https://www.cloudamqp.com/blog/2015-09-03-part4-rabbitmq-for-beginners-exchanges-routing-keys-bindings.html
https://www.rabbitmq.com/tutorials/tutorial-four-python.html

**Comment by blankdots** [comment]
The `basic.ack` or `basic.reject` should come after the processing of the message.
The message should be rejected, error logged and if there is an RPC style of communication a reply message sent back.
